package com.artemis.demo.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class Orders {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long orderID;

    @ManyToOne
    @JoinColumn(name = "userID", nullable = false)
    private User user;

    @ManyToMany
    @JoinTable(
        name = "orders_products", // Join table name
        joinColumns = @JoinColumn(name = "orderID"), // Foreign key for ShoppingCart
        inverseJoinColumns = @JoinColumn(name = "productID") // Foreign key for Product
    )
    private List<Product> items;  // List of items in the cart

    private BigDecimal totalPrice;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false, updatable = false)
    private Date createdAt = new Date();

    @OneToOne
    @JoinColumn(name = "cart_id", unique = true)
    private ShoppingCart shoppingCart;

    // Getters and Setters (generated by Lombok)
}
