package com.artemis.demo.model;

import java.math.BigDecimal;
import java.util.List;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class ShoppingCart {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long cartID;

    @OneToOne
    @JoinColumn(name = "userID", nullable = false, unique = true)
    private User user;  // Associated User

    @ManyToMany
    @JoinTable(
        name = "shopping_cart_products", // Join table name
        joinColumns = @JoinColumn(name = "cartID"), // Foreign key for ShoppingCart
        inverseJoinColumns = @JoinColumn(name = "productID") // Foreign key for Product
    )
    private List<Product> items;  // List of items in the cart

    private BigDecimal totalPrice = BigDecimal.ZERO;  // Total price of items in the cart

    public void recalculateTotalPrice() {
        totalPrice = items.stream()
            .map(Product::getPrice) // Assuming `Product` has a `getPrice()` method
            .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    // Getters and Setters (generated by Lombok)
}
